default: &default
  adapter: postgresql
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  encoding: utf8
  min_messages: warning

development:
  <<: *default
  database: action_cable_development

test:
  <<: *default
  database: action_cable_test

production: &deploy
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
